export const FETCH_SHOPPING_LIST = "FETCH_SHOPPING_LIST";
export const DELECT_SHOPPING_LIST_ITEM = "DELECT_SHOPPING_LIST_ITEM";
export const DELECT_SHOPPING_LIST_ITEM_SUCCES = "DELECT_SHOPPING_LIST_ITEM_SUCCES";
export const SWITCH_ITEM_BOUGHT_STATUS = "SWITCH_ITEM_BOUGHT_STATUS";
export const CLEAR_SELECTION = "CLEAR_SELECTION";
export const TOGGLE_EDIT = "TOGGLE_EDIT";
export const TOGGLE_DELETE_DIALOG ="TOGGLE_DELETE_DIALOG";
